name: Bug Report 🐛
description: Create a bug report for this repository
title: "[BUG]: "
labels: ["bug"]
assignees: ["fredericrous"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill a bug report.
        Make sure there aren't any open/closed issues for this topic
        Please first verify your issue can be reproduce on the latest version

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: input
    attributes:
      label: What version are you using?
      description: 'For example: 1.2.1'
    validations:
      required: true

  - type: textarea
    attributes:
      label: What environment are you running?
      description: Give as much details as possible. ex: What OS are you on?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as logs and screenshots
